server:
  port: ${PORT:8080}

spring:
  profiles:
    active: dev

  config:
    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        highlight_sql: true

