spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}/${DB_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


  backend:
    url: ${BACKEND_URL}
  frontend:
    url: ${FRONTEND_URL}