spring:

  jwt:
    secret: ${JWT_SECRET}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        highlight_sql: true

  datasource:
    url: jdbc:mariadb://${DB_URL}/${DB_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${BACKEND_URL}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            provider: naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  backend:
    url: ${BACKEND_URL}

  frontend:
    url: ${FRONTEND_URL}

server:
  port: ${PORT:8080}
