server:
  port: ${PORT:8080}

spring:

  config:
    import: application-secret.yml, application-db.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        highlight_sql: true

  backend:
    url: ${BACKEND_URL}
  frontend:
    url: ${FRONTEND_URL}